application:
  title: "TradeX : Trading Made Easy"
  version: 1.0

app:
  nodehealth:
    monitor:
      schedule: 0,15,30,45 * * * * *
  load_mock_data: ${APP_LOAD_MOCK_DATA:true}
  load_balance: ${APP_DB_LOADBALANCE:true}
  mylocation: ${APP_INSTANCE_LOCATION:WASHINGTON}
  datasource_types: ${DATASOURCE_TYPES:MULTI_REGION_MULTI_ZONE}
  security:
    jwt:
      secret: cccccclvkgnllrhrngucjbivrehvjcnkfvfihildhfcg
      expiry: 86400
  cors:
    max_age: 3600
  yb:
    api:
      host: ${YB_API_HOST}
      custid: ${YB_API_CUST}
      authtoken: ${YB_API_TOKEN}

spring:
  application:
    name: trading-api

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        connection:
          provider_disables_autocommit: true
        default_schema: public
    open-in-view: false
  thymeleaf:
    prefix: classpath:/static/

  data:
    rest:
      base-path: /api/v1
  devtools:
    livereload:
      port: 35730

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


server:
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/xml,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  error:
    whitelabel:
      enabled: false


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      #    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
      springframework:
        security: debug
        web:
          client: info
        sql: DEBUG
        cache: WARN
        beans:
          factory:
            config:
              PropertiesFactoryBean: DEBUG
    com:
      zaxxer:
        hikari: WARN
      yugabyte:
        ysql: WARN
        samples:
          tradex: DEBUG
---
spring:
  config:
    activate:
      on-profile: SR & yugabyte
  datasource:
    sr:
      url: jdbc:yugabytedb://127.0.0.1:5433/tradex_sr
      driver-class-name: com.yugabyte.Driver
      username: yugabyte
      password: yugabyte
      hikari:
        maximumPoolSize: 50
        maxLifeTime: 3600000
        data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
        data-source-properties:
          additionalEndpoints: 127.0.0.2:5433,127.0.0.3:5433
          topologyKeys: "cloud1.datacenter1.rack1"

app:
  datasource_types: SINGLE_REGION_MULTI_ZONE

---
spring:
  config:
    activate:
      on-profile: MR & yugabyte
  datasource:
    mr:
      url: jdbc:yugabytedb://127.0.0.1:5433/tradex_mr
      driver-class-name: com.yugabyte.Driver
      username: yugabyte
      password: yugabyte
      hikari:
        maximumPoolSize: 50
        maxLifeTime: 3600000
        data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
        data-source-properties:
          additionalEndpoints: 127.0.0.2:5433,127.0.0.3:5433,127.0.0.4:5433
          topologyKeys: "aws.us-east-1.*,aws.us-east-2.*"
app:
  datasource_types: MULTI_REGION_MULTI_ZONE
  mylocation: BOSTON
---
spring:
  config:
    activate:
      on-profile: MR & yugabyte & west
  datasource:
    mr:
      hikari:
        data-source-properties:
          topologyKeys: "aws.us-west-1.*,aws.us-west-2.*"
app:
  mylocation: WASHINGTON
---
spring:
  config:
    activate:
      on-profile: MR & yugabyte & west & dev
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: GEO & yugabyte
  datasource:
    mr:
      url: jdbc:yugabytedb://127.0.0.1:5433/tradex_geo
      driver-class-name: com.yugabyte.Driver
      username: yugabyte
      password: yugabyte
      hikari:
        maximumPoolSize: 50
        maxLifeTime: 3600000
        data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
        data-source-properties:
          additionalEndpoints: 127.0.0.2:5433,127.0.0.3:5433,127.0.0.4:5433
          topologyKeys: "aws.us-east-1.*,aws.us-east-2.*"
app:
  datasource_types: GEO_PARTITIONED
  mylocation: BOSTON
---
spring:
  config:
    activate:
      on-profile: GEO & yugabyte & west
  datasource:
    mr:
      hikari:
        data-source-properties:
          topologyKeys: "aws.us-west-1.*,aws.us-west-2.*"
  app:
    mylocation: WASHINGTON
---
spring:
  config:
    activate:
      on-profile: GEO & yugabyte & west & dev
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: MRRR & yugabyte
  datasource:
    mrrr:
      url: jdbc:yugabytedb://127.0.0.1:5433/tradex_mrrr
      driver-class-name: com.yugabyte.Driver
      username: yugabyte
      password: yugabyte
      hikari:
        maximumPoolSize: 50
        maxLifeTime: 3600000
        data-source-class-name: com.yugabyte.ysql.YBClusterAwareDataSource
        data-source-properties:
          serverName: 127.0.0.1
          portNumber: 5433
          databaseName: mercury
          additionalEndpoints: 127.0.0.2:5433,127.0.0.3:5433
          topologyKeys: "aws.*"
---
spring:
  config:
    activate:
      on-profile: SR & oracle
